
package hung.webservicetest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceTest", targetNamespace = "http://webserviceTest.hung/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceTest {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceInfo", targetNamespace = "http://webserviceTest.hung/", className = "hung.webservicetest.GetServiceInfo")
    @ResponseWrapper(localName = "getServiceInfoResponse", targetNamespace = "http://webserviceTest.hung/", className = "hung.webservicetest.GetServiceInfoResponse")
    @Action(input = "http://webserviceTest.hung/WebServiceTest/getServiceInfoRequest", output = "http://webserviceTest.hung/WebServiceTest/getServiceInfoResponse")
    public String getServiceInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
